GET http://localhost:3030/usuarios

### register
POST http://localhost:3030/usuarios
Content-Type: application/json

{
    "nombre":"robert",
    "password":"castellano12",
    "email":"robert@robert.com"
}

### login
POST http://localhost:3030/usuarios/login
Content-Type: application/json

{
    "password":"castellano12",
    "email":"emerson@emerson.com"
}